# -*- coding: utf-8 -*-
"""integrales.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tqaHSPZpyQMPWUvNXyu_GjRP7b2INBjq

Se desea desarrollar una competencia de integrales en una Universidad. Para motivar a los estudiantes sin importar el nivel, se desea que inicialmente los problemas sean sencillos. Para esto se ha seleccionado un problema y se le ha preguntado a n personas sus opiniones. Si al menos una persona dijo que el problema era difícil el problema será difícil y se procederá a cambiar dicho ejercicio.

Entrada: La primera línea contiene la cantidad n de personas que dieron su opinión sobre un problema dado. La siguiente línea contiene n números que pueden ser 0 o 1. Si es un cero la persona piensa que el problema es fácil, si es un 1, la persona piensa que es un problema difícil: Salida Muestre la palabra FACIL si el problema es fácil de acuerdo con las respuestas dadas o DIFICIL si al menos una persona piensa que el problema es difícil.

<table style="width:100%">
  <tr>
    <th>INPUT</th>
    <th>OUTPUT</th> 
  </tr>
  <tr>
    <td style="text-align:center">3</td>
    <td style="text-align:center">Fácil</td>
  </tr>
  <tr>
    <td style="text-align:center">101</td>
    <td style="text-align:center"></td>
  </tr>
</table>
"""

import sys

def output_(m):
  if m.count('1',0,len(m))>=1:
    return True
  else:
    return False

def main():
  n=input() #"Ingrese numero de personas: "
  m=input() #"Ingrese 0 ó 1: "

  if output_(m) == True:
    print("DIFICIL",sep="")
  else:
    print("FACIL",sep="")

if __name__== "__main__" :
    main()